import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { SiteNav } from "@/components/site-nav";
import { Ticker } from "@/components/ui/ticker";
import {
  TradeIncomingResult,
  TradeOutboundResult,
} from "@/components/decision/result-card";
import {
  fetchSharedVerdict,
  isValidShortCode,
  publicVerdictUrl,
  recordVerdictView,
} from "@/lib/share/trade-verdict-share";
import type {
  TradeIncomingOutput,
  TradeOutboundOutput,
} from "@/lib/engine/schemas";

export const dynamic = "force-dynamic";

type PageProps = {
  params: Promise<{ code: string }>;
};

export async function generateMetadata(
  { params }: PageProps,
): Promise<Metadata> {
  const { code } = await params;
  if (!isValidShortCode(code)) {
    return { title: "Verdict not found", robots: { index: false } };
  }
  const record = await fetchSharedVerdict(code);
  if (!record) {
    return { title: "Verdict not found", robots: { index: false } };
  }
  const headline =
    record.mode === "incoming"
      ? extractIncomingHeadline(record.output as TradeIncomingOutput)
      : extractOutboundHeadline(record.output as TradeOutboundOutput);
  const url = publicVerdictUrl(record.short_code);
  return {
    title: `${headline} · Dynasty General`,
    description:
      record.mode === "incoming"
        ? "Calibrated dynasty trade verdict. Methodology and backtest at dynastygeneral.app/scoreboard."
        : "Calibrated dynasty trade attack plan. Methodology and backtest at dynastygeneral.app/scoreboard.",
    alternates: { canonical: url },
    openGraph: {
      title: `${headline} · Dynasty General`,
      description: `${Math.round((record.confidence ?? 50))}% confidence · Engine v0 · 0.399 Spearman, beats consensus`,
      url,
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title: `${headline} · Dynasty General`,
      description: `${Math.round((record.confidence ?? 50))}% confidence · Engine v0 · 0.399 Spearman, beats consensus`,
    },
    robots: { index: false, follow: true },
  };
}

function extractIncomingHeadline(o: TradeIncomingOutput): string {
  const action = o.action.toUpperCase();
  return `${action}: ${o.recommendation.slice(0, 80)}`;
}

function extractOutboundHeadline(o: TradeOutboundOutput): string {
  return `Attack: ${o.attack_angle.slice(0, 90)}`;
}

export default async function SharedVerdictPage({ params }: PageProps) {
  const { code } = await params;
  if (!isValidShortCode(code)) notFound();

  const record = await fetchSharedVerdict(code);
  if (!record) notFound();

  // Bump engagement counter. Fire-and-forget; never blocks render.
  // OG image fetches (separate route segment) do not call this, so
  // social-platform unfurls don't inflate the counter.
  recordVerdictView(code).catch(() => {});

  const sharedAt = new Date(record.created_at).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  const tickerLabel =
    record.team_display
      ? `Trade verdict from ${record.team_display} · ${sharedAt}`
      : `Trade verdict · ${sharedAt}`;

  return (
    <>
      <SiteNav />
      <main className="flex-1 bg-background">
        <section className="border-b border-border-soft">
          <div className="mx-auto max-w-3xl px-6 pt-16 pb-10 sm:pt-20">
            <Ticker label={tickerLabel} />
            <h1 className="mt-6 text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
              {record.mode === "incoming"
                ? "Should they take this deal?"
                : "Attack a target."}
            </h1>
            <p className="mt-4 max-w-2xl text-muted">
              This is a trade verdict generated by Dynasty General. The
              recommendation, opponent read, and walk-away floor are the
              same payload that was shown to the team owner at the time
              they ran the analysis. Methodology and accuracy are public.
            </p>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-3xl px-6 py-10">
            {record.mode === "incoming" ? (
              <TradeIncomingResult
                result={record.output as TradeIncomingOutput}
                mode="live"
              />
            ) : (
              <TradeOutboundResult
                result={record.output as TradeOutboundOutput}
                mode="live"
              />
            )}
          </div>
        </section>

        <section className="border-t border-border-soft">
          <div className="mx-auto max-w-3xl px-6 py-10">
            <div className="rounded-lg border border-border-soft bg-surface px-6 py-5">
              <p className="text-sm text-muted">
                Want a verdict like this on your own dynasty trade?
              </p>
              <p className="mt-2 text-base text-foreground">
                Dynasty General reads your Sleeper league, considers
                format rules, format-multiplied pick values, roster
                construction, and three-source consensus. Every trade
                verdict is anchored in a public backtest.
              </p>
              <div className="mt-4 flex flex-wrap items-center gap-3">
                <Link
                  href="/connect"
                  className="inline-flex h-9 items-center rounded-md border border-border-strong bg-surface px-3 text-xs font-medium text-foreground transition hover:border-accent/60 hover:text-accent"
                >
                  Open the app →
                </Link>
                <Link
                  href="/scoreboard"
                  className="font-mono text-[11px] uppercase tracking-[0.16em] text-muted-2 hover:text-foreground"
                >
                  See the scoreboard →
                </Link>
                <Link
                  href="/how-it-works"
                  className="font-mono text-[11px] uppercase tracking-[0.16em] text-muted-2 hover:text-foreground"
                >
                  How it works →
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
